### PR TITLE
(mini.surround): Support multi line surround.

### PR DESCRIPTION
**Pull request by wodesuck**
- [x] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [x] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by echasnovski** [comment]
Thank you so much for this! I'd implement this from the start if new it doesn't add *that* much complexity.

Buuut... This is a really crazy coincidence. *Today* I have started coding for #103 and the first step is to implement multiline surroundings. Which I am wrapping up right now (ended up mostly similar to your solution). It will get merged after all work #103 is done.

Sorry, but I am going with my solution. This ended up as the prime example of why I ask people to open an issue before doing a PR :(

**Comment by wodesuck** [comment]
Nevermind, glad to hear that #103 is going to be done.

**Comment by echasnovski** [comment]
If you are curious with what I ended up, you can take a look as [surround-ai-backend](https://github.com/echasnovski/mini.nvim/tree/surround-ai-backend) branch.

Thanks again for your effort, though! I really appreciate it.

**Comment by echasnovski** [comment]
Update 'mini.surround' is now merged in `main` branch.

**Pull request closed without merging**
