### PR TITLE
refactor!: remove nvim-ts dependency

### PR DESCRIPTION
**Pull request by amaanq**
- [x] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [x] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

The new nvim-ts main branch removes a lot of the functionality and brings many performance improvements, but it is not the default branch for now, and won't be for a while. Though, after 0.10 master is pretty much deprecated, and plugins should not depend on nvim-ts utilities besides locals...this will also allow users to use the main branch without these plugins breaking. Thanks!

### CODE REVIEW

**Comment by clason** [comment]
Note: `locals.lua` is also not guaranteed to be kept in nvim-treesitter 1.0; only the queries will (most likely) be maintained.

If there are (widely) useful utility functions missing, they should be considered for inclusion in the core API.

**Comment by echasnovski** [comment]
> The new nvim-ts main branch removes a lot of the functionality and brings many performance improvements, but it is not the default branch for now, and won't be for a while. Though, after 0.10 master is pretty much deprecated, and plugins should not depend on nvim-ts utilities besides locals...this will also allow users to use the main branch without these plugins breaking. Thanks!

Thanks the PR!

To be honest, I am not keen on making braking changes for the not stable work-in-progress branch which is not the default yet. Besides, all proposed changes address tree-sitter based functionality which can choose what approach to use through `opts.use_nvim_treesitter`. If users want/need to use `main` 'nvim-treesitter' branch, I'd recommend using `opts.use_nvim_treesitter = false` for now.

@clason, the one utility function used in 'mini.ai' and 'mini.surround' which I can not find in Nightly is `require('nvim-treesitter.query').get_capture_matches_recursively()`. Is this considered to be a (widely) used utility function?

**Comment by clason** [comment]
Is this a breaking change though? The user-facing behavior should not change, except that users can (but don't have to) drop nvim-treesitter if the "bring their own parser".

> require('nvim-treesitter.query').get_capture_matches_recursively(). Is this considered to be a (widely) used utility function?

Not sure; if someone were to make a PR, a quick GH search would tell them. It would also depend on whether this can be easily replicated using already provided functions.

**Comment by echasnovski** [comment]
> Is this a breaking change though? The user-facing behavior should not change, except that users can (but don't have to) drop nvim-treesitter if they "bring their own parser".

I would assume that such change would require new tree-sitter utilities ported from 'nvim-treesitter' into Neovim core, which makes it a hard dependence on nightly (hence breaking for others Neovim versions). The code in PR seems like a direct copy-paste from 'nvim-treesitter' source code, so can't judge beyond that.

**Comment by amaanq** [comment]
It is just copy-pasted, so it wouldn't be breaking for now

**Comment by clason** [comment]
That being said, there's no particular urgency; the deprecation of the legacy nvim-treesitter won't be happening until after the Nvim 0.10 release, probably sometime (late) this summer.

**Comment by clason** [comment]
> It is just copy-pasted (slightly adjusted), so it wouldn't be breaking for now

Yeah, that's not good enough; you need an actual refactor of the calling code based on current Neovim API. I'd recommend closing this PR and trying again later.

**Comment by amaanq** [comment]
the adjusted bit is adjusted for the current Neovim API

**Comment by clason** [comment]
You did not adjust the actual code at all (or sufficiently, it looks like); just a copy-paste leaving references to internal nvim-treesitter code...

**Comment by amaanq** [comment]
oh yeah...I relied on lsp too much, will close for now, my bad

**Comment by clason** [comment]
@amaanq If you permit me to be blunt: this PR is a bit of an ill-considered hip shot. The first step should be to look at our own `nvim-treesitter-textobjects` and do a proper refactor of this (in a separate `main` branch). After this is done (possibly including upstreaming utility functions), we can take the lessons learned to the broader ecosystem.

**Comment by amaanq** [comment]
yeah that's a good idea, that'd also give me a better sense of how to refactor for nvim-ts main going forward

**Pull request closed without merging**
