### PR TITLE
(mini.ai) Allow to match whitespaces for argument textobject

### PR DESCRIPTION
**Pull request by tobiwild**
Can be enabled via:

custom_textobjects = {
    a = require('mini.ai').gen_spec.argument({ match_whitespaces = true }),
}

- [ ] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [ ] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by echasnovski** [comment]
Thanks for this PR! This looks very promising.

I'll look through it for possibly unexpected pitfalls and get back here.

**Comment by echasnovski** [comment]
Hi, @tobiwild!

I have finally found time and motivation to work on this.

The exact changes in your PR couldn't be merged because they break some important features (like allow matching while cursor is on the first and last whitespaces **but** don't include them in textobject). But your approach of refactoring to handle separator spans instead of points gave me a push to implement support of full Lua patterns as separator instead of single characters.

Changes are in [ai-separator-span](https://github.com/echasnovski/mini.nvim/tree/ai-separator-span) branch. It has soft deprecation of `separators` (plural) option in favor of `separator` (singluar) one. You use case of matching whitespace should be covered with this setup:

```lua
local ai = require('mini.ai')
ai.setup({
  custom_textobjects = {
    a = ai.gen_spec.argument({ separator = '%s*,%s*' }),
  },
})
```

Could you, please, test it on your end? I plan to merge it latest by the end of the week. Thanks!

**Comment by tobiwild** [comment]
@echasnovski I was now able to test it and I like it. This is even more flexible and doesn't require some special `match_whitespaces` option. Thanks for the change, I guess this PR can now be closed :)

**Comment by echasnovski** [comment]
> @echasnovski I was now able to test it and I like it. This is even more flexible and doesn't require some special `match_whitespaces` option. Thanks for the change, I guess this PR can now be closed :)

Thanks for the feedback!

I'll wait till tomorrow in case an unexpected issues arise. They probably won't, but just in case :)

**Comment by echasnovski** [comment]
This is now in `main`.
Thanks for the implementation idea and push to do it!

**Pull request closed without merging**
