### PR TITLE
feat(icons): add `mock_lspkind` to emulate `lspkind.nvim`

### PR DESCRIPTION
**Pull request by mehalter**
- [x] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [x] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

This takes a stab at adding `lspkind` emulation to `mini.icons` to help integrate it with more plugins. There are only 2 API functions which make it a really nice candidate for emulation. This also adds some tests to make sure that the 2 functions work. Let me know what you think or if you have any recommendations to improve this.

Thanks for such a great icons module 🥳

### CODE REVIEW

**Comment by echasnovski** [comment]
Thanks for the PR!

I was asked several times about this feature already. I'd need to do some research first.
Plan to take it myself from here, thanks!

**Comment by mehalter** [comment]
Awesome, thanks! I am definitely one of the people who have asked as well. Figured I would help with the maintenance burden since I'm fairly familiar with the `lspkind` plugin and help get the ball rolling 😄 I'll at least make sure the tests are passing here to help provide code you can use if you want or completely ignore if you prefer to write it all yourself!

Not sure what the error is on the Document generation, I thought I touched all of the files necessary to correctly generate the documentation. If you do want to use this and want me to fix up the document generation let me know what I might be missing and I can fix that up. Whatever makes your life easiest :D

**Comment by echasnovski** [comment]
@mehalter, thanks for the efforts. I'll take it from here, no need to workload poor CI.

**Comment by mehalter** [comment]
No worries, all the tests pass ❤️

**Comment by echasnovski** [comment]
@mehalter, please stop pushing to this PR. This both gives me unnecessary notifications to react to and adds a lot of finished CI jobs to plough through to find the ones I am interested in.

I am not yet entirely convinced that this will be added to 'mini.icons'. I need time for research and making decision first. I'll take it from here. Thanks!

**Comment by mehalter** [comment]
So sorry for the noise! I was simply maintaining my separate fork with the latest changes since I actively use this branch for the time being. I was under the impression that you should be able to control notifications by unsubscribing since I think notifications only come from PRs because it automatically subscribes by default. I will go ahead and make a separate branch on my fork and do my own maintenance and stop pushing here. 

Again I'm so sorry! Was not meaning to pester 😞

**Comment by echasnovski** [comment]
No worries! I *really* appreciate the efforts. It's just I currently need more time to get to this, because fixing issues in 'mini.icons' has more priority than adding new features.

> I was under the impression that you should be able to control notifications by unsubscribing...

I'd still would like to know what's going on in comments here.

**Comment by echasnovski** [comment]
@mehalter, I've finally reached the point of having mental capacity to review this PR. Sorry it took so long.

My original plan for even adding "lsp" category was for it to have effect on 'mini.completion'. After studying the code of 'onsails/lspkind.nvim', I've noticed that it plainly overrides `vim.lsp.protocol.CompletionItemKind` and it seems to work. As this map is also used in 'mini.completion', this was a good sign.

In the end, I opted for adding a specific `MiniIcons.tweak_lsp_kind()` and tie it to 'mini.completion'. All other parts of 'onsails/lspkind.nvim' are either straightforward to implement manually (`M.symbolic()`) or rather out of scope for 'mini.icons' (`M.cmp_format()`, as only single line concerns icons while the rest are convenience wrappers for formatting completion item).

I appreciate the work you've put into this PR, but I am afraid it won't get merged in favor of functionality already present in `main`. Thanks for the effort!

**Pull request closed without merging**
