### PR TITLE
fix(pairs): consider using `lazyredraw` to prevent cursor flickering

### PR DESCRIPTION
**Pull request by 39555**
Temporarily toggle `vim.o.lazyredraw = true` while inserting pairs to prevent weird cursor flickering

- [x] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [x] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Before this pr

I reduced the video speed to 1/4. The cursor jumping forth and back drives me nuts))

https://github.com/user-attachments/assets/2ef07b04-cea1-4c51-8535-8502a65ba859

### After this pr

The screen will be redrawn only on the next tick. Similar to your using of  `vim.o.eventignore`

https://github.com/user-attachments/assets/8a902893-6886-42f3-9dd8-345c66eb2a21

### CODE REVIEW

**Comment by echasnovski** [comment]
Thanks for the PR!

Having the `lazyredraw` temporarily set on almost every 'mini.pairs' related occasions is a bit too much. The `eventignore` workaround was necessary to not trigger `InsertLeave` event which can result in big lags (see #839) and it is only triggered when pressing `<CR>` inside registered pair, which is not that much.

And I also can not reproduce this cursor jumping. Can you reproduce this with only 'mini.pairs' enabled? Because I suspect the real reason for the lag is the rainbow coloring of brackets. For example, see #196.

**Comment by 39555** [comment]
I can reproduce with tree-sitter enabled `:=vim.treesitter.start()` with just mini.pairs, with your dotfiles and with LazyVim
1. `git clone --filter=blob:none https://github.com/echasnovski/nvim.git ~/.config/nvim-mini`
2. `NVIM_APPNAME=nvim-mini nvim init.lua`
3. `:=vim.treesitter.start()`

```
NVIM v0.11.0-nightly+bcae8be
Build type: Release
LuaJIT 2.1.1713773202
```


https://github.com/user-attachments/assets/609f7b78-5797-45bc-a1e2-e820ad866b74

Lets wait maybe someone also has such an issue. 

> is a bit too much

Is switching options or `schedule_wrap` expensive here? TIL

**Comment by echasnovski** [comment]
> I can reproduce with tree-sitter enabled `:=vim.treesitter.start()` with just mini.pairs

Yes, I can *kind of* reproduce this with tree-sitter enabled, but it depends on the size of a file. At the end of large file (like 'lua/mini/pick.lua') it is indeed fairly consistent, but in smaller file - not so much.

> Is switching options or `schedule_wrap` expensive here? TIL

Well, for starters, `schedule_wrap()` doesn't do what you assume it would do :) It creates a wrapper function that executes its input inside `vim.schedule()`. See `vim.o.eventignore` approach.

But the option switch is kind of costly. I'd need to benchmark to decided based on numbers.

For the 'eventignore' case it was around 0.002 ms when triggered inside registered pair, which is ok. Here it will be invoked fairly more frequently, so need to think if removing this (not entirely consistent) flicker is worth it.

------

Are **all** calls of `H.with_lazyredraw()` needed? For example, I don't think they are needed before moving cursor to the right. The same goes for `<BS>`.

I can not reproduce the issue with the following diff:

```diff
diff --git a/lua/mini/pairs.lua b/lua/mini/pairs.lua
index 5bea3c9..45c196a 100644
--- a/lua/mini/pairs.lua
+++ b/lua/mini/pairs.lua
@@ -281,6 +281,10 @@ end
 MiniPairs.open = function(pair, neigh_pattern)
   if H.is_disabled() or not H.neigh_match(neigh_pattern) then return pair:sub(1, 1) end
 
+  local cache_lazyredraw = vim.go.lazyredraw
+  vim.go.lazyredraw = true
+  H.restore_lazyredraw(cache_lazyredraw)
+
   return ('%s%s'):format(pair, H.get_arrow_key('left'))
 end
 
@@ -641,5 +645,6 @@ H.map = function(mode, lhs, rhs, opts)
 end
 
 H.restore_eventignore = vim.schedule_wrap(function(val) vim.o.eventignore = val end)
+H.restore_lazyredraw = vim.schedule_wrap(function(val) vim.go.lazyredraw = val end)
 
 return MiniPairs
```

Could you, please, check if there are any visible lags left after applying this change?

**Comment by 39555** [comment]
Yeah, using it only inside `MiniPairs.open` is sufficient

**Comment by echasnovski** [comment]
Thanks for changes!

I'll ponder a bit on this at least until the next 0.14.0 release.

**Comment by 39555** [comment]
Evgeni, can you tell me what the benchmark you used looked like? I came across different variations of this but failed to get reliable results.

```bash
#!/usr/bin/env bash

function run() {
    nvim --clean -c 'lua _G.package.path = [[./lua/?.lua;]] .. _G.package.path' -c 'lua require("mini.pairs").setup({})'  -u './benchmark.lua' -c 'e ./lua/mini/pick.lua' -c 'lua vim.treesitter.start()'
}

git checkout pairs-lazyredraw
run
git checkout main
run


```

```lua
-- ./benchmark.lua
local key = vim.api.nvim_replace_termcodes('(', true, true, false)
local runs = 1000000

local function benchmark(callback)
  local start_time = vim.uv.hrtime()
  for _ = 0, runs, 1 do
    callback()
  end
  return (vim.uv.hrtime() - start_time) / 1e6 -- microseconds
end

run = function()
    vim.cmd.startinsert()

    local r = benchmark((function() vim.api.nvim_feedkeys(key, 'i', false) end)
    vim.notify(('%.9f'):format(r / runs), vim.log.levels.INFO)
    vim.cmd([[qa!]])
end

vim.schedule(run, 100)

```

**Comment by echasnovski** [comment]
> Evgeni, can you tell me what the benchmark you used looked like? I came across different variations of this but failed to get reliable results.

Not so much elaborated ones :)

Basically:
- Add `_G.log = {}` somewhere inside 'lua/mini/pairs.lua'.
- Add `local start_time = vim.loop.hrtime()` before `local cache_lazyredraw = vim.go.lazyredraw`.
- Add `table.insert(_G.log, 0.000001 * (vim.loop.hrtime() - start_time))` after `H.restore_lazyredraw(cache_lazyredraw)`.
- Restart Neovim and try inserting opening characters. Then look at `_G.log` times (they are in milliseconds).

This approach is more indicative of which delays are present during interactive session.

**Comment by flukeeey** [comment]
> > I can reproduce with tree-sitter enabled `:=vim.treesitter.start()` with just mini.pairs
> 
> Yes, I can _kind of_ reproduce this with tree-sitter enabled, but it depends on the size of a file. At the end of large file (like 'lua/mini/pick.lua') it is indeed fairly consistent, but in smaller file - not so much.
> 
> > Is switching options or `schedule_wrap` expensive here? TIL
> 
> Well, for starters, `schedule_wrap()` doesn't do what you assume it would do :) It creates a wrapper function that executes its input inside `vim.schedule()`. See `vim.o.eventignore` approach.
> 
> But the option switch is kind of costly. I'd need to benchmark to decided based on numbers.
> 
> For the 'eventignore' case it was around 0.002 ms when triggered inside registered pair, which is ok. Here it will be invoked fairly more frequently, so need to think if removing this (not entirely consistent) flicker is worth it.
> 
> Are **all** calls of `H.with_lazyredraw()` needed? For example, I don't think they are needed before moving cursor to the right. The same goes for `<BS>`.
> 
> I can not reproduce the issue with the following diff:
> 
> ```diff
> diff --git a/lua/mini/pairs.lua b/lua/mini/pairs.lua
> index 5bea3c9..45c196a 100644
> --- a/lua/mini/pairs.lua
> +++ b/lua/mini/pairs.lua
> @@ -281,6 +281,10 @@ end
>  MiniPairs.open = function(pair, neigh_pattern)
>    if H.is_disabled() or not H.neigh_match(neigh_pattern) then return pair:sub(1, 1) end
>  
> +  local cache_lazyredraw = vim.go.lazyredraw
> +  vim.go.lazyredraw = true
> +  H.restore_lazyredraw(cache_lazyredraw)
> +
>    return ('%s%s'):format(pair, H.get_arrow_key('left'))
>  end
>  
> @@ -641,5 +645,6 @@ H.map = function(mode, lhs, rhs, opts)
>  end
>  
>  H.restore_eventignore = vim.schedule_wrap(function(val) vim.o.eventignore = val end)
> +H.restore_lazyredraw = vim.schedule_wrap(function(val) vim.go.lazyredraw = val end)
>  
>  return MiniPairs
> ```
> 
> Could you, please, check if there are any visible lags left after applying this change?

Applying this diff fixed some very noticeable and jarring flickering when opening new pairs. :+1:

**Comment by echasnovski** [comment]
I've been daily driving these changes (with also a similar `lazyredraw` switch in `cr()`, as there are flickering there also) for about a week now and didn't notice any obvious performance or usability issues.

The actual benchmarking shows the same level of delay as for 'eventignore', but it is not on 0.002 ms scale as I mentioned earlier: more like 0.04 ms for me. Still relatively fast, although `open()` mappings are used more often than `cr()`.

Let's hope that there will be no performance issues or issues with macros / any other programmatic usage of these keys.

I've merged it into separate branch to polish a bit. It should appear in `main` soon.

Thanks again for finding this interesting workaround for the flickering problem!

**Pull request merged**
