### PR TITLE
docs(jump2d): fix typo

### PR DESCRIPTION
**Pull request by lostl1ght**
- [x] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [x] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by lostl1ght** [comment]
> This will need adjusting the source file too.

Right! Thanks for telling me. I've adjusted the source file.

**Comment by echasnovski** [comment]
> > This will need adjusting the source file too.
> 
> Right! Thanks for telling me. I've adjusted the source file.

The modeline in help (txt) file should not be changed. Did you use 'mini.doc' to generate it (as described in 'CONTRIBUTING.md'?

**Comment by lostl1ght** [comment]
To be honest, I skimmed through it 😅 
I've regenerated docs.

**Comment by echasnovski** [comment]
Thanks again for the PR! This should be part of `main` branch now.

**Comment by lostl1ght** [comment]
My pleasure!

**Pull request merged**
